### ISSUE TITLE
Misleading clickable pointer mouse cursor

### ISSUE THREAD

**Issue by linkfanel** [joergdietrich/Leaflet.Terminator#15]
By default, when hovering the mouse over the terminator overlay, the mouse cursor changes to the clickable pointer. This provides a poor user experience: it gives a misleading and distracting visual cue that the dark area would be something to interact with, and it also deprives from the proper visual cue of the cursor changing to clickable when hovering over an actually clickable marker on the dark side.

This can be fixed by passing `interactive: false` in the constructor options: "If false, the layer will not emit mouse events and will act as a part of the underlying map." (https://leafletjs.com/reference-1.6.0.html#polygon-interactive) I'm not fully sure of all the effects, but I would suggest adding this to the default Terminator options (where it can still be overridden), or at least documenting it in the README (and at least it's documented in this issue now).

**Comment by joergdietrich** [comment]
Thank you for noticing this and opening the issue! Your proposed solution looks good to me. Would you be willing to create a pull request for this?

**Comment by joergdietrich** [comment]
Closed via #17
