### ISSUE TITLE
How to remove terminator from the map?

### ISSUE THREAD

**Issue by KEVISONG** [joergdietrich/Leaflet.Terminator#19]
Hey guys.

This plugin is great. But I can't figure out how to remove the overlay from the map after adding it.
I tried terminator().remove() but it didn't work. May be I did wrong.

Please advice! thx.

**Comment by joergdietrich** [comment]
You need to assign the terminator to a variable:
```
var t = L.terminator()
```

Then `t.remove()` will work. Note not parentheses after `t`.
